[package]
name    = "yubikey-piv"
version = "0.0.2" # Also update html_root_url in lib.rs when bumping this
description = """
Pure Rust host-side driver for the YubiKey Personal Identity Verification (PIV)
application providing general-purpose public-key signing and encryption
with hardware-backed private keys for RSA (2048/1024) and ECC (P-256/P-384)
algorithms (e.g, PKCS#1v1.5, ECDSA)
"""
authors    = ["Tony Arcieri <bascule@gmail.com>", "Yubico AB"]
edition    = "2018"
license    = "BSD-2-Clause"
repository = "https://github.com/iqlusioninc/yubikey-piv.rs"
readme     = "README.md"
categories = ["api-bindings", "cryptography", "hardware-support"]
keywords   = ["ccid", "ecdsa", "rsa", "piv", "yubikey"]

[badges]
maintenance = { status = "experimental" }

[dependencies]
der-parser = "3"
des = "0.3"
ecdsa = "0.1"
getrandom = "0.1"
hmac = "0.7"
log = "0.4"
nom = "5"
pbkdf2 = "0.3"
pcsc = "2"
rsa = "0.1.4"
secrecy = "0.5"
sha-1 = "0.8"
subtle = "2"
x509-parser = "0.6"
zeroize = "1"

[dev-dependencies]
env_logger = "0.7"

[features]
untested = []

[package.metadata.docs.rs]
all-features = true
