[package]
name = "yubikey-cli"
version = "0.0.0"
description = """
Command-line interface for performing encryption and signing using RSA and/or
ECC keys stored on YubiKey devices.
"""
authors = ["Tony Arcieri <bascule@gmail.com>"]
edition = "2018"
license = "BSD-2-Clause"
repository = "https://github.com/iqlusioninc/yubikey-piv.rs"
readme     = "README.md"
categories = ["command-line-utilities", "cryptography", "hardware-support"]
keywords   = ["ecdsa", "rsa", "piv", "pcsc", "yubikey"]

[dependencies]
gumdrop = "0.7"
env_logger = "0.7"
lazy_static = "1"
termcolor = "1"
yubikey-piv = { version = "0.0.3", path = ".." }
